name: C/C++ CI

on:
  push:
    branches:
      - Fix-aarch64-build2
  pull_request:
    branches:
      - Fix-aarch64-build2

jobs:
  build:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash -el {0}
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: 'flame/blis'
        ref: '8820f8f91efd32e38e2995e73323656ef767bbd8'
    - name: configure
      run: ./configure piledriver
    - name: make
      run: make
    - name: make install
      run: sudo make install

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: 'rmast/pytorch'
        ref: 'Fix-aarch64-build2'
        submodules: 'recursive'

    - uses: conda-incubator/setup-miniconda@v3
      with:
        auto-activate-base: true
        activate-environment: true
        python-version: 3.10.13

    - name: Install Dependencies - Common - Linux 2
      run: |
        conda info
        conda list
        conda install nomkl
        conda install astunparse numpy ninja pyyaml setuptools cmake cffi typing_extensions future six requests dataclasses
        export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}
        export BLAS=BLIS

        export USE_RCCL=1
        export USE_NCCL=1
        export USE_KINETO=1

        export CMAKE_ARGS="-D CMAKE_BUILD_TYPE=Release -DBUILD_LIBTORCH_CPU_WITH_DEBUG=0 -DBUILD_PYTHON=True -DBUILD_PYTHONLESS= -DBUILD_TEST=True -DUSE_CUDA=0 -DUSE_FBGEMM=1 -DUSE_GLOO_WITH_OPENSSL=ON -DUSE_GOLD_LINKER=ON -DUSE_KINETO=1 -DUSE_NCCL=1 -DUSE_NUMPY=True -DUSE_RCCL=1 -DUSE_SPLIT_BUILD=false -DPYTHON_INCLUDE_DIR=$(python -c "import sysconfig; print(sysconfig.get_path('include'))") -DPYTHON_LIBRARY=$(python -c "import sysconfig; print(sysconfig.get_config_var('LIBDIR'))") -DPYTHON_EXECUTABLE:FILEPATH=`which python`"
        pip install build wheel typing_extensions
        python setup.py bdist_wheel
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-without-markdown
        path: |
          dist
          !dist/**/*.md
